apiVersion: v1
kind: Service
metadata:
  name: moviereviewservice

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: moviereview

  ports:
    - name: http
      port: 8086
      nodePort: 30012

  type: LoadBalancer
