apiVersion: v1
kind: Service
metadata:
  name: moviereviewservice

spec:
  selector:
    app: moviereview
    # give this when there is pods and service for selector and labels --
    #release: 0


  ports:
  - name: http
    port: 8086
# if you are running on any cloud provider remove the nodePort and change type as LoadBalancer
  type: LoadBalancer
